[package]
name = "ingestor"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = {version = "2.0.13", features = ["abigen", "ipc", "rustls", "ws"] }
openssl = "0.10.64"
eyre = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36", features = ["full", "macros"] }
log = "0.4"
anyhow = { version = "1.0" }
simple_logger = "4.3"

sea-orm = { version = "^0", features = [ "sqlx-postgres", "runtime-tokio-native-tls", "macros", "debug-print" ] }
migration = { path = "migration" }