[package]
name = "ingestor"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = {version = "1.0.2", features = ["abigen", "ipc", "rustls", "ws"] }
openssl = "0.10.64"
eyre = "0.6"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = { version = "1.25", features = ["full", "macros"] }
log = "0.4.17"
anyhow = { version = "1.0.69" }
simple_logger = "4.0.0"

sea-orm = { version = "^0", features = [ "sqlx-postgres", "runtime-tokio-native-tls", "macros", "debug-print" ] }
migration = { path = "migration" }